# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.grpc import session_exchange_interface_pb2 as main_dot_services_dot_session__exchange__interface__pb2


class SessionExchangeSimulatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamExchangeData = channel.unary_stream(
                '/session_exchange.SessionExchangeSimulator/StreamExchangeData',
                request_serializer=main_dot_services_dot_session__exchange__interface__pb2.StreamRequest.SerializeToString,
                response_deserializer=main_dot_services_dot_session__exchange__interface__pb2.ExchangeDataUpdate.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/session_exchange.SessionExchangeSimulator/Heartbeat',
                request_serializer=main_dot_services_dot_session__exchange__interface__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=main_dot_services_dot_session__exchange__interface__pb2.HeartbeatResponse.FromString,
                )
        self.GetHealth = channel.unary_unary(
                '/session_exchange.SessionExchangeSimulator/GetHealth',
                request_serializer=main_dot_services_dot_session__exchange__interface__pb2.HealthRequest.SerializeToString,
                response_deserializer=main_dot_services_dot_session__exchange__interface__pb2.HealthResponse.FromString,
                )
        self.GetSessionStatus = channel.unary_unary(
                '/session_exchange.SessionExchangeSimulator/GetSessionStatus',
                request_serializer=main_dot_services_dot_session__exchange__interface__pb2.SessionStatusRequest.SerializeToString,
                response_deserializer=main_dot_services_dot_session__exchange__interface__pb2.SessionStatusResponse.FromString,
                )


class SessionExchangeSimulatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamExchangeData(self, request, context):
        """Single unified stream for all exchange data - user-aware with broadcasting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Enhanced heartbeat with session status information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Health check with service and user status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionStatus(self, request, context):
        """New: Get session connection status for a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionExchangeSimulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamExchangeData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamExchangeData,
                    request_deserializer=main_dot_services_dot_session__exchange__interface__pb2.StreamRequest.FromString,
                    response_serializer=main_dot_services_dot_session__exchange__interface__pb2.ExchangeDataUpdate.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=main_dot_services_dot_session__exchange__interface__pb2.HeartbeatRequest.FromString,
                    response_serializer=main_dot_services_dot_session__exchange__interface__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=main_dot_services_dot_session__exchange__interface__pb2.HealthRequest.FromString,
                    response_serializer=main_dot_services_dot_session__exchange__interface__pb2.HealthResponse.SerializeToString,
            ),
            'GetSessionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionStatus,
                    request_deserializer=main_dot_services_dot_session__exchange__interface__pb2.SessionStatusRequest.FromString,
                    response_serializer=main_dot_services_dot_session__exchange__interface__pb2.SessionStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'session_exchange.SessionExchangeSimulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SessionExchangeSimulator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamExchangeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/session_exchange.SessionExchangeSimulator/StreamExchangeData',
            main_dot_services_dot_session__exchange__interface__pb2.StreamRequest.SerializeToString,
            main_dot_services_dot_session__exchange__interface__pb2.ExchangeDataUpdate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/session_exchange.SessionExchangeSimulator/Heartbeat',
            main_dot_services_dot_session__exchange__interface__pb2.HeartbeatRequest.SerializeToString,
            main_dot_services_dot_session__exchange__interface__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/session_exchange.SessionExchangeSimulator/GetHealth',
            main_dot_services_dot_session__exchange__interface__pb2.HealthRequest.SerializeToString,
            main_dot_services_dot_session__exchange__interface__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/session_exchange.SessionExchangeSimulator/GetSessionStatus',
            main_dot_services_dot_session__exchange__interface__pb2.SessionStatusRequest.SerializeToString,
            main_dot_services_dot_session__exchange__interface__pb2.SessionStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
