version: '3.8'

services:
  frontend-gateway:
    build:
      context: ./frontend_dist
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - NODE_ENV=production
      - API_URL=http://api-server:8080
      - WS_URL=ws://api-server:8080
    depends_on:
      - api-server
    volumes:
      - ./frontend_dist:/app
    command: node gateway.config.js

  api-server:
    # Your existing API server configuration
    image: your-api-server:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}