apiVersion: v1
kind: Service
metadata:
  name: iexg-market-data-gateway
  labels:
    app: iexg-market-data-gateway
spec:
  ports:
    - port: 50551
      name: api
  clusterIP: None
  selector:
    app: iexg-market-data-gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: iexg-market-data-gateway
  labels:
    app: iexg-market-data-gateway
spec:
  serviceName: "iexg-market-data-gateway"
  replicas: 2
  selector:
    matchLabels:
      app: iexg-market-data-gateway
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: iexg-market-data-gateway
        servicetype: market-data-gateway
        mic: IEXG
    spec:
      serviceAccountName: trading-services
      containers:
        - name: iexg-market-data-gateway
          image: ${DOCKER_REPO}/otp-market-data-gateway-fixsim:${VERSION}
          env:
            - name: FIX_SIM_ADDRESS
              value: iexgsimulator:50051
            - name: GATEWAY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 50551
              name: api
            - containerPort: 8080
              name: metrics
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
