apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 5775
          protocol: UDP
          name: agent-udp
        - containerPort: 6831
          protocol: UDP
          name: agent-thrift
        - containerPort: 6832
          protocol: UDP
          name: agent-binary
        - containerPort: 5778
          name: agent-http
        - containerPort: 16686
          name: query
        - containerPort: 14268
          name: collector
        - containerPort: 14250
          name: grpc
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: "9411"
        - name: MEMORY_MAX_TRACES
          value: "10000"
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  labels:
    app: jaeger
spec:
  ports:
  - port: 16686
    targetPort: 16686
    name: query
  selector:
    app: jaeger
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  labels:
    app: jaeger
spec:
  ports:
  - port: 14268
    targetPort: 14268
    name: collector-http
  - port: 14250
    targetPort: 14250
    name: collector-grpc
  - port: 9411
    targetPort: 9411
    name: collector-zipkin
  selector:
    app: jaeger
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  labels:
    app: jaeger
spec:
  ports:
  - port: 5775
    targetPort: 5775
    protocol: UDP
    name: agent-udp
  - port: 6831
    targetPort: 6831
    protocol: UDP
    name: agent-thrift
  - port: 6832
    targetPort: 6832
    protocol: UDP
    name: agent-binary
  - port: 5778
    targetPort: 5778
    name: agent-http
  selector:
    app: jaeger
  type: ClusterIP