apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  labels:
    app: authorization-service
spec:
  ports:
    - name: auth
      port: 4000
      protocol: TCP
      targetPort: auth
    - name: grpc
      port: 50551
      protocol: TCP
      targetPort: grpc
  selector:
    app: authorization-service
  sessionAffinity: ClientIP
