# k8s/deployments/auth-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: opentp/auth-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: pgbouncer  # Changed from postgres to pgbouncer for connection pooling
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: opentp
        - name: DB_USER
          value: opentp
        - name: DB_PASSWORD
          value: samaral
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-jwt-secret
              key: JWT_SECRET
        - name: JWT_REFRESH_SECRET  # Added JWT refresh secret
          valueFrom:
            secretKeyRef:
              name: auth-jwt-secret
              key: JWT_REFRESH_SECRET
        resources:  # Added resource limits
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:  # Added health check
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:  # Added health check
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP