apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-simulator
  template:
    metadata:
      labels:
        app: exchange-simulator
    spec:
      containers:
      - name: exchange-simulator
        image: opentp/exchange-simulator:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50055
---
apiVersion: v1
kind: Service
metadata:
  name: exchange-simulator
spec:
  selector:
    app: exchange-simulator
  ports:
  - port: 50055
    targetPort: 50055
  type: ClusterIP