# k8s/deployments/fund-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fund-service
spec:
  replicas: 2  # Multiple replicas for horizontal scaling
  selector:
    matchLabels:
      app: fund-service
  template:
    metadata:
      labels:
        app: fund-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: fund-service
        image: opentp/fund-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001  # REST service
        - containerPort: 9091  # Prometheus metrics
        env:
        - name: DB_HOST
          value: pgbouncer  # Using connection pooling
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: opentp
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: MINIO_ENDPOINT
          value: "storage-service:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: storage-credentials
              key: access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: storage-credentials
              key: secret-key
        - name: MINIO_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: storage-credentials
              key: bucket-name
        - name: SESSION_SERVICE_URL
          value: "http://session-service:8080"
        - name: AUTH_SERVICE_URL
          value: http://auth-service:8000
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: "http://jaeger-collector:14268/api/traces"
        - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
          value: "jaeger-agent"
        - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
          value: "6831"
        - name: OTEL_SERVICE_NAME
          value: "fund-service"
        - name: ENABLE_TRACING
          value: "true"
        - name: ENABLE_METRICS
          value: "true"
        - name: METRICS_PORT
          value: "9091"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
      initContainers:
      - name: wait-for-db
        image: postgres:13
        command: ['sh', '-c', 'until pg_isready -h pgbouncer -p 5432; do echo waiting for database; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: fund-service
spec:
  selector:
    app: fund-service
  ports:
  - name: http
    port: 8001
    targetPort: 8001
  - name: metrics
    port: 9091
    targetPort: 9091
  type: ClusterIP