apiVersion: batch/v1
kind: CronJob
metadata:
  name: risk-model-service-daily
spec:
  schedule: "0 2 * * *"  # Every day at 2:00 AM UTC
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: risk-model-service
            job-type: batch
        spec:
          initContainers:
          - name: wait-for-db
            image: postgres:13
            command: ['sh', '-c', 'until pg_isready -h pgbouncer -p 5432; do echo waiting for database; sleep 2; done;']
          containers:
          - name: risk-model-service
            image: opentp/risk-model-service:latest
            imagePullPolicy: Never
            env:
            - name: DB_HOST
              value: pgbouncer
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: opentp
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: ENVIRONMENT
              value: "production"
            - name: LOG_LEVEL
              value: "INFO"
            - name: OTEL_SERVICE_NAME
              value: "risk-model-service-batch"
            - name: ENABLE_TRACING
              value: "true"
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 5  # Keep last 5 successful runs
  failedJobsHistoryLimit: 3      # Keep last 3 failed runs