# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main/auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmain/auth.proto\"F\n\x0cLoginRequest\x12\x1a\n\x08username\x18\x01 \x01(\tR\x08username\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\"d\n\rLoginResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x14\n\x05token\x18\x02 \x01(\tR\x05token\x12#\n\rerror_message\x18\x03 \x01(\tR\x0c\x65rrorMessage\"%\n\rLogoutRequest\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token\"*\n\x0eLogoutResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\",\n\x14ValidateTokenRequest\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token\"F\n\x15ValidateTokenResponse\x12\x14\n\x05valid\x18\x01 \x01(\x08R\x05valid\x12\x17\n\x07user_id\x18\x02 \x01(\tR\x06userId2\xa0\x01\n\x0b\x41uthService\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12)\n\x06Logout\x12\x0e.LogoutRequest\x1a\x0f.LogoutResponse\x12>\n\rValidateToken\x12\x15.ValidateTokenRequest\x1a\x16.ValidateTokenResponseB\rB\tAuthProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main.auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\tAuthProtoP\001'
  _LOGINREQUEST._serialized_start=19
  _LOGINREQUEST._serialized_end=89
  _LOGINRESPONSE._serialized_start=91
  _LOGINRESPONSE._serialized_end=191
  _LOGOUTREQUEST._serialized_start=193
  _LOGOUTREQUEST._serialized_end=230
  _LOGOUTRESPONSE._serialized_start=232
  _LOGOUTRESPONSE._serialized_end=274
  _VALIDATETOKENREQUEST._serialized_start=276
  _VALIDATETOKENREQUEST._serialized_end=320
  _VALIDATETOKENRESPONSE._serialized_start=322
  _VALIDATETOKENRESPONSE._serialized_end=392
  _AUTHSERVICE._serialized_start=395
  _AUTHSERVICE._serialized_end=555
# @@protoc_insertion_point(module_scope)
