apiVersion: v1
kind: Service
metadata:
  name: exchange-simulator
  labels:
    app: exchange-simulator
spec:
  selector:
    app: exchange-simulator
  ports:
  - port: 50055
    targetPort: 50055
    name: grpc
  - port: 50056
    targetPort: 50056
    name: http
  type: ClusterIP