apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: default
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  REST_PORT: "8001"
  
  # Database Configuration
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "orders"
  DB_MIN_CONNECTIONS: "2"
  DB_MAX_CONNECTIONS: "20"
  
  # Redis Configuration
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service:8000"
  
  # Performance settings
  REQUEST_TIMEOUT: "30"
  
  # Feature flags
  ENABLE_METRICS: "true"