apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: default
type: Opaque
data:
  # These values would be base64 encoded and managed via a secure method
  # Example values shown here should not be used in production
  DB_USER: b3BlbnRw  # 'opentp' base64 encoded
  DB_PASSWORD: c2FtYXJhbA==  # 'samaral' base64 encoded
  REDIS_PASSWORD: ""  # No password in this example