# k8s/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trading-platform-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Session affinity for WebSockets
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "trading_session"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
    # WebSocket settings
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    # WebSocket headers (replacing configuration-snippet)
    nginx.ingress.kubernetes.io/enable-websocket: "true"
spec:
  rules:
  - host: trading.local
    http:
      paths:
      - path: /api/auth/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth-service
            port:
              number: 8000
      - path: /api/session/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: session-manager
            port:
              number: 8080
      - path: /api/orders/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: order-service
            port:
              number: 8001
      - path: /ws/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: session-manager
            port:
              number: 8088
      - path: /api/stream/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: session-manager
            port:
              number: 8088
      # Admin dashboard and monitoring paths
      - path: /admin/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: admin-dashboard
            port:
              number: 80
      - path: /prometheus/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: prometheus
            port:
              number: 9090
      - path: /grafana/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: grafana
            port:
              number: 3000
      # Create a dedicated path for Jaeger static assets
      - path: /jaeger/static/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: jaeger-query
            port:
              number: 16686
      # Then the regular Jaeger path
      - path: /jaeger/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: jaeger-query
            port:
              number: 16686
      - path: /minio/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: minio
            port:
              number: 9000