apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: default
  labels:
    app: session-service
spec:
  selector:
    app: session-service
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP