apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: postgresql
data:
  pgbouncer.ini: |
    [databases]
    * = host=opentp-postgresql.postgresql dbname=opentp

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 5432
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    pool_mode = transaction
    max_client_conn = 1000
    default_pool_size = 20
    min_pool_size = 5
    reserve_pool_size = 10
    reserve_pool_timeout = 5
    server_reset_query = DISCARD ALL
    server_check_delay = 30
    server_check_query = SELECT 1
    server_lifetime = 3600
    server_idle_timeout = 600
    log_disconnections = 1
    log_connections = 1
    application_name_add_host = 1
    stats_period = 60
    ignore_startup_parameters = extra_float_digits

  userlist.txt: |
    "opentp" "md5$(echo -n "passwordopentp" | md5sum | cut -d ' ' -f 1)"