apiVersion: v1
kind: Secret
metadata:
  name: auth-jwt-secret
type: Opaque
stringData:
  JWT_SECRET: "8UNJze4hic63V+Bc6eLESFxnNE5Uyu5TKz0BIpEDctQ="
  JWT_REFRESH_SECRET: "vbAb9rFPqWYgSduCWzn0NzFCdn/otjLx7bDjX1SZFFk="
