apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-monitor
  labels:
    app: order-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-monitor
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: order-monitor
    spec:
      serviceAccountName: trading-services
      containers:
        - name: order-monitor
          image: ${DOCKER_REPO}/otp-order-monitor:${VERSION}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: opentp-common
          ports:
            - name: grpc
              containerPort: 50551
            - name: metrics
              containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 5
            periodSeconds: 10
