postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: latest
  auth:
    username: opentp
    password: password
    database: opentp
  primary:
    persistence:
      enabled: true
      size: 8Gi
  metrics:
    enabled: true
  volumePermissions:
    enabled: true
  pgHbaConfiguration: |
    local   all             all                                     trust
    host    all             all             127.0.0.1/32           trust
    host    all             all             ::1/128                trust
    host    all             all             0.0.0.0/0             md5
  initdbScriptsConfigMap: postgresql-init-scripts
