{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "envoy.fullname" . }}
  labels:
    {{- include "envoy.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: admin
      path: /stats/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      {{- include "envoy.selectorLabels" . | nindent 6 }}
{{- end }}