apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-config-service
  labels:
    app: client-config-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-config-service
  template:
    metadata:
      labels:
        app: client-config-service
    spec:
      serviceAccountName: trading-services
      containers:
        - name: client-config-service
          image: ${DOCKER_REPO}/otp-client-config-service:${VERSION}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: opentp-common
          ports:
            - name: grpc
              containerPort: 50551
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 5
            periodSeconds: 10
