apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trading-services-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
