apiVersion: v1
kind: Service
metadata:
  name: market-data-service
  labels:
    app: market-data-service
spec:
  ports:
    - name: grpc
      port: 50551
      targetPort: grpc
  selector:
    app: market-data-service
  sessionAffinity: ClientIP
