apiVersion: v1
kind: Service
metadata:
  name: order-data-service
  labels:
    app: order-data-service
spec:
  ports:
    - name: grpc
      port: 50551
      protocol: TCP
      targetPort: grpc
  selector:
    app: order-data-service
