apiVersion: v1
kind: Service
metadata:
  name: quote-aggregator
  labels:
    app: quote-aggregator
spec:
  ports:
    - port: 50551
      name: api
  clusterIP: None
  selector:
    app: quote-aggregator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quote-aggregator
  labels:
    app: quote-aggregator
spec:
  serviceName: "quote-aggregator"
  replicas: 2
  selector:
    matchLabels:
      app: quote-aggregator
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: quote-aggregator
        servicetype: market-data-gateway
        mic: XOSR
    spec:
      serviceAccountName: trading-services
      containers:
        - name: quote-aggregator
          image: ${DOCKER_REPO}/otp-quote-aggregator:${VERSION}
          imagePullPolicy: Always
          env:
            - name: GATEWAY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: opentp-common
          ports:
            - containerPort: 50551
              name: api
            - containerPort: 8080
              name: metrics
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
