# k8s/config/db-schemas-crypto.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-schemas-crypto
data:
  crypto.sql: |
    -- Crypto Schema
    CREATE SCHEMA IF NOT EXISTS crypto;

    -- User-Wallet relationship table
    CREATE TABLE crypto.wallets (
      user_id UUID NOT NULL REFERENCES auth.users(user_id) ON DELETE CASCADE,
      fund_id UUID NOT NULL REFERENCES fund.funds(fund_id) ON DELETE CASCADE,
      address TEXT NOT NULL,
      mnemonic TEXT NOT NULL,
      mnemonic_salt TEXT NOT NULL,
      active_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
      expire_at TIMESTAMP WITH TIME ZONE DEFAULT '2999-01-01',
      PRIMARY KEY (user_id, fund_id),
      UNIQUE(address)
    );

  
    CREATE INDEX IF NOT EXISTS idx_crypto_wallets_user_id ON crypto.wallets(user_id);
    CREATE INDEX IF NOT EXISTS idx_crypto_wallets_fund_id ON crypto.wallets(fund_id);

    -- User-Contracts relationship table
    CREATE TABLE crypto.contracts (
      contract_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      user_id UUID NOT NULL REFERENCES auth.users(user_id) ON DELETE CASCADE,
      book_id UUID NOT NULL REFERENCES fund.books(book_id) ON DELETE CASCADE,
      app_id TEXT NOT NULL,
      app_address TEXT NOT NULL,
      parameters TEXT,
      status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
      blockchain_status VARCHAR(50) NOT NULL DEFAULT 'Active',
      active_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
      expire_at TIMESTAMP WITH TIME ZONE DEFAULT '2999-01-01',
      deleted_at TIMESTAMP WITH TIME ZONE,
      deletion_note TEXT,
      UNIQUE(app_address)
    );

    CREATE INDEX IF NOT EXISTS idx_crypto_contracts_user_id ON crypto.contracts(user_id);
    CREATE INDEX IF NOT EXISTS idx_crypto_contracts_fund_id ON crypto.contracts(fund_id);
    CREATE INDEX IF NOT EXISTS idx_crypto_contracts_app_id ON crypto.contracts(app_id);
    
    CREATE TABLE crypto.txs (
      tx_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      user_id UUID NOT NULL REFERENCES auth.users(user_id),
      book_id UUID NOT NULL REFERENCES fund.books(book_id),
      contract_id UUID NOT NULL REFERENCES crypto.contracts(contract_id) ON DELETE CASCADE,
      app_id TEXT NOT NULL,
      transaction_id TEXT NOT NULL,
      date TIMESTAMP WITH TIME ZONE NOT NULL,

      sender TEXT NOT NULL,
      action VARCHAR(50) NOT NULL,
      
      g_user_id VARCHAR(255),
      g_book_id VARCHAR(255),
      g_status VARCHAR(50),
      g_params VARCHAR(255),

      l_book_hash VARCHAR(255),
      l_research_hash VARCHAR(255),
      l_params VARCHAR(255),
      
      created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
      UNIQUE(transaction_id)
    );

    CREATE TABLE crypto.supplemental (
      tx_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      user_id UUID NOT NULL REFERENCES auth.users(user_id),
      fund_id UUID NOT NULL REFERENCES fund.funds(fund_id),
      contract_id UUID NOT NULL REFERENCES crypto.contracts(contract_id) ON DELETE CASCADE,
      app_id TEXT NOT NULL,
      transaction_id TEXT NOT NULL,
      date TIMESTAMP WITH TIME ZONE NOT NULL,

      conviction_file_path TEXT,
      conviction_file_encoded TEXT,

      research_file_path TEXT,
      research_file_encoded TEXT,

      notes TEXT,
      notes_encoded TEXT,
      
      UNIQUE(transaction_id)
    );
  
    CREATE INDEX IF NOT EXISTS idx_crypto_txs_user_id ON crypto.txs(user_id);
    CREATE INDEX IF NOT EXISTS idx_crypto_txs_fund_id ON crypto.txs(fund_id);
    CREATE INDEX IF NOT EXISTS idx_crypto_txs_contract_id ON crypto.txs(contract_id);
    CREATE INDEX IF NOT EXISTS idx_crypto_txs_app_id ON crypto.txs(app_id);
    CREATE INDEX IF NOT EXISTS idx_crypto_txs_date ON crypto.txs(date);
        
    -- Grant permissions
    GRANT USAGE ON SCHEMA crypto TO opentp;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA crypto TO opentp;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA crypto TO opentp;
    ALTER DEFAULT PRIVILEGES IN SCHEMA crypto GRANT ALL ON TABLES TO opentp;
    ALTER DEFAULT PRIVILEGES IN SCHEMA crypto GRANT ALL ON SEQUENCES TO opentp;