apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-config
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      jaeger:
        endpoint: jaeger-collector:14250
        tls:
          insecure: true
    processors:
      batch:
      memory_limiter:
        limit_mib: 100
        check_interval: 5s
    extensions:
      health_check:
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [jaeger]