apiVersion: v1
kind: ConfigMap
metadata:
  name: opentp-common
  namespace: default
data:
  # Kafka Configuration
  KAFKA_BROKERS: "kafka-opentp-0.kafka-opentp-headless.kafka.svc.cluster.local:9092,kafka-opentp-1.kafka-opentp-headless.kafka.svc.cluster.local:9092,kafka-opentp-2.kafka-opentp-headless.kafka.svc.cluster.local:9092"
  KAFKA_ORDERS_TOPIC: "orders"

  # Application Configuration
  LOG_LEVEL: "info"

  # Feature Flags
  METRICS_ENABLED: "true"
