apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentp-frontend
  labels:
    app: opentp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentp-frontend
  template:
    metadata:
      labels:
        app: opentp-frontend
    spec:
      serviceAccountName: trading-services
      containers:
        - name: frontend
          image: ${REGISTRY}/opentp-frontend:${TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
