apiVersion: v1
kind: Service
metadata:
  name: opentp-frontend
  labels:
    app: opentp-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: opentp-frontend
