envoy:
  replicaCount: 2

  service:
    type: LoadBalancer
    ports:
      http:
        port: 10000
        targetPort: 10000
        protocol: TCP
      admin:
        port: 9901
        targetPort: 9901
        protocol: TCP

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

  config:
    envoy.yaml: |
      admin:
        access_log_path: /tmp/admin_access.log
        address:
          socket_address: { address: 0.0.0.0, port_value: 9901 }

      static_resources:
        listeners:
        - name: listener_0
          address:
            socket_address: { address: 0.0.0.0, port_value: 10000 }
          filter_chains:
          - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: grpc_routes
                  virtual_hosts:
                  - name: grpc_services
                    domains: ["*"]
                    routes:
                    - match: { prefix: "/loginservice.LoginService" }
                      route:
                        cluster: authorization-service-cluster
                    - match: { prefix: "/executionvenue.ExecutionVenue" }
                      route:
                        cluster: order-router-cluster
                    - match: { prefix: "/marketdataservice.MarketDataService" }
                      route:
                        cluster: market-data-service-cluster
                http_filters:
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

        clusters:
        - name: authorization-service-cluster
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: authorization-service-cluster
            endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: authorization-service
                      port_value: 50551
