# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from source.api.grpc import order_exchange_interface_pb2 as main_dot_services_dot_order__exchange__interface__pb2


class OrderExchangeSimulatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitOrder = channel.unary_unary(
                '/order_exchange.OrderExchangeSimulator/SubmitOrder',
                request_serializer=main_dot_services_dot_order__exchange__interface__pb2.SubmitOrderRequest.SerializeToString,
                response_deserializer=main_dot_services_dot_order__exchange__interface__pb2.SubmitOrderResponse.FromString,
                )
        self.CancelOrder = channel.unary_unary(
                '/order_exchange.OrderExchangeSimulator/CancelOrder',
                request_serializer=main_dot_services_dot_order__exchange__interface__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=main_dot_services_dot_order__exchange__interface__pb2.CancelOrderResponse.FromString,
                )


class OrderExchangeSimulatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitOrder(self, request, context):
        """Submit an order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Cancel an order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderExchangeSimulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOrder,
                    request_deserializer=main_dot_services_dot_order__exchange__interface__pb2.SubmitOrderRequest.FromString,
                    response_serializer=main_dot_services_dot_order__exchange__interface__pb2.SubmitOrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=main_dot_services_dot_order__exchange__interface__pb2.CancelOrderRequest.FromString,
                    response_serializer=main_dot_services_dot_order__exchange__interface__pb2.CancelOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order_exchange.OrderExchangeSimulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderExchangeSimulator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_exchange.OrderExchangeSimulator/SubmitOrder',
            main_dot_services_dot_order__exchange__interface__pb2.SubmitOrderRequest.SerializeToString,
            main_dot_services_dot_order__exchange__interface__pb2.SubmitOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_exchange.OrderExchangeSimulator/CancelOrder',
            main_dot_services_dot_order__exchange__interface__pb2.CancelOrderRequest.SerializeToString,
            main_dot_services_dot_order__exchange__interface__pb2.CancelOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
