# k8s/podpolicies/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: session-manager-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: session-manager
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: order-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: auth-service