apiVersion: v1
kind: Service
metadata:
  name: iexg-order-gateway
  labels:
    app: iexg-order-gateway
spec:
  ports:
    - port: 50551
      name: api
  clusterIP: None
  selector:
    app: iexg-order-gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: iexg-order-gateway
  labels:
    app: iexg-order-gateway
spec:
  serviceName: "iexg-order-gateway"
  replicas: 2
  selector:
    matchLabels:
      app: iexg-order-gateway
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: iexg-order-gateway
        servicetype: execution-venue
        mic: IEXG
    spec:
      serviceAccountName: trading-services
      containers:
        - name: iexg-order-gateway
          image: ${DOCKER_REPO}/otp-fix-sim-execution-venue:${VERSION}
          envFrom:
            - configMapRef:
                name: opentp-common
          env:
            - name: FIX_SOCKET_CONNECT_HOST
              value: iexgsimulator
            - name: FIX_SOCKET_CONNECT_PORT
              value: "9876"
            - name: FIX_LOG_FILE_PATH
              value: /open-trading-platform/iexg-order-gateway
            - name: FIX_FILE_STORE_PATH
              value: /open-trading-platform/iexg-order-gateway
            - name: MIC
              value: IEXG
            - name: ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /open-trading-platform
              name: execution-venue-storage
          ports:
            - containerPort: 50551
              name: api
            - containerPort: 8080
              name: metrics
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
      volumes:
        - name: execution-venue-storage
          emptyDir: {}
