# k8s/jobs/db-init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:13
        command:
          - "/bin/bash"
          - "-c"
          - |
            echo "Starting database initialization..."
            
            # Apply schema files in order
            echo "Applying schema files..."
            PGPASSWORD=samaral psql -h postgres -U opentp -d opentp -f /schemas/users.sql
            PGPASSWORD=samaral psql -h postgres -U opentp -d opentp -f /schemas/sessions.sql
            PGPASSWORD=samaral psql -h postgres -U opentp -d opentp -f /schemas/simulator_sessions.sql
            PGPASSWORD=samaral psql -h postgres -U opentp -d opentp -f /schemas/auth_tokens.sql
            
            # Apply data files
            echo "Applying data files..."
            PGPASSWORD=samaral psql -h postgres -U opentp -d opentp -f /data/auth_functions.sql
            PGPASSWORD=samaral psql -h postgres -U opentp -d opentp -f /data/users.sql
            
            echo "Database initialization completed."
        volumeMounts:
        - name: db-schemas
          mountPath: /schemas
        - name: db-data
          mountPath: /data
      volumes:
      - name: db-schemas
        configMap:
          name: db-schemas
      - name: db-data
        configMap:
          name: db-data
      restartPolicy: OnFailure