# k8s/jobs/db-init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:13
        command:
          - "/bin/bash"
          - "-c"
          - |
            echo "Starting database initialization..."
            
            # Wait for database to be fully ready
            until PGPASSWORD=$(cat /db-credentials/password) psql -h postgres -U $(cat /db-credentials/username) -d opentp -c "SELECT 1" > /dev/null 2>&1; do
              echo "Waiting for PostgreSQL to be ready..."
              sleep 2
            done
            
            # Apply schema files in order
            echo "Applying schema files..."
            PGPASSWORD=$(cat /db-credentials/password) psql -h postgres -U $(cat /db-credentials/username) -d opentp -f /schemas/users.sql
            PGPASSWORD=$(cat /db-credentials/password) psql -h postgres -U $(cat /db-credentials/username) -d opentp -f /schemas/sessions.sql
            PGPASSWORD=$(cat /db-credentials/password) psql -h postgres -U $(cat /db-credentials/username) -d opentp -f /schemas/simulator_sessions.sql
            PGPASSWORD=$(cat /db-credentials/password) psql -h postgres -U $(cat /db-credentials/username) -d opentp -f /schemas/auth_tokens.sql
            
            # Apply data files
            echo "Applying data files..."
            PGPASSWORD=$(cat /db-credentials/password) psql -h postgres -U $(cat /db-credentials/username) -d opentp -f /data/auth_functions.sql
            PGPASSWORD=$(cat /db-credentials/password) psql -h postgres -U $(cat /db-credentials/username) -d opentp -f /data/users.sql
            
            echo "Database initialization completed successfully."
        volumeMounts:
        - name: db-schemas
          mountPath: /schemas
        - name: db-data
          mountPath: /data
        - name: db-credentials
          mountPath: /db-credentials
          readOnly: true
      volumes:
      - name: db-schemas
        configMap:
          name: db-schemas
      - name: db-data
        configMap:
          name: db-data
      - name: db-credentials
        secret:
          secretName: db-credentials
      restartPolicy: OnFailure