// session_manager.proto

// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file main/session_manager.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file main/session_manager.proto.
 */
export const file_main_session_manager: GenFile = /*@__PURE__*/
  fileDesc("ChptYWluL3Nlc3Npb25fbWFuYWdlci5wcm90byI2ChRDcmVhdGVTZXNzaW9uUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgJEg0KBXRva2VuGAIgASgJIlMKFUNyZWF0ZVNlc3Npb25SZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEhIKCnNlc3Npb25faWQYAiABKAkSFQoNZXJyb3JfbWVzc2FnZRgDIAEoCSI2ChFHZXRTZXNzaW9uUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJEg0KBXRva2VuGAIgASgJIl8KEkdldFNlc3Npb25SZXNwb25zZRIWCg5zZXNzaW9uX2FjdGl2ZRgBIAEoCBIaChJzaW11bGF0b3JfZW5kcG9pbnQYAiABKAkSFQoNZXJyb3JfbWVzc2FnZRgDIAEoCSI2ChFFbmRTZXNzaW9uUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJEg0KBXRva2VuGAIgASgJIjwKEkVuZFNlc3Npb25SZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEhUKDWVycm9yX21lc3NhZ2UYAiABKAkiNQoQS2VlcEFsaXZlUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJEg0KBXRva2VuGAIgASgJIiQKEUtlZXBBbGl2ZVJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgiOwoWR2V0U2Vzc2lvblN0YXRlUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJEg0KBXRva2VuGAIgASgJIqQBChdHZXRTZXNzaW9uU3RhdGVSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEhQKDHNpbXVsYXRvcl9pZBgCIAEoCRIaChJzaW11bGF0b3JfZW5kcG9pbnQYAyABKAkSGgoSc2Vzc2lvbl9jcmVhdGVkX2F0GAQgASgDEhMKC2xhc3RfYWN0aXZlGAUgASgDEhUKDWVycm9yX21lc3NhZ2UYBiABKAkyvwIKFVNlc3Npb25NYW5hZ2VyU2VydmljZRI+Cg1DcmVhdGVTZXNzaW9uEhUuQ3JlYXRlU2Vzc2lvblJlcXVlc3QaFi5DcmVhdGVTZXNzaW9uUmVzcG9uc2USNQoKR2V0U2Vzc2lvbhISLkdldFNlc3Npb25SZXF1ZXN0GhMuR2V0U2Vzc2lvblJlc3BvbnNlEjUKCkVuZFNlc3Npb24SEi5FbmRTZXNzaW9uUmVxdWVzdBoTLkVuZFNlc3Npb25SZXNwb25zZRIyCglLZWVwQWxpdmUSES5LZWVwQWxpdmVSZXF1ZXN0GhIuS2VlcEFsaXZlUmVzcG9uc2USRAoPR2V0U2Vzc2lvblN0YXRlEhcuR2V0U2Vzc2lvblN0YXRlUmVxdWVzdBoYLkdldFNlc3Npb25TdGF0ZVJlc3BvbnNlQhdCE1Nlc3Npb25NYW5hZ2VyUHJvdG9QAWIGcHJvdG8z");

/**
 * @generated from message CreateSessionRequest
 */
export type CreateSessionRequest = Message<"CreateSessionRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string token = 2;
   */
  token: string;
};

/**
 * Describes the message CreateSessionRequest.
 * Use `create(CreateSessionRequestSchema)` to create a new message.
 */
export const CreateSessionRequestSchema: GenMessage<CreateSessionRequest> = /*@__PURE__*/
  messageDesc(file_main_session_manager, 0);

/**
 * @generated from message CreateSessionResponse
 */
export type CreateSessionResponse = Message<"CreateSessionResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string session_id = 2;
   */
  sessionId: string;

  /**
   * @generated from field: string error_message = 3;
   */
  errorMessage: string;
};

/**
 * Describes the message CreateSessionResponse.
 * Use `create(CreateSessionResponseSchema)` to create a new message.
 */
export const CreateSessionResponseSchema: GenMessage<CreateSessionResponse> = /*@__PURE__*/
  messageDesc(file_main_session_manager, 1);

/**
 * @generated from message GetSessionRequest
 */
export type GetSessionRequest = Message<"GetSessionRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string token = 2;
   */
  token: string;
};

/**
 * Describes the message GetSessionRequest.
 * Use `create(GetSessionRequestSchema)` to create a new message.
 */
export const GetSessionRequestSchema: GenMessage<GetSessionRequest> = /*@__PURE__*/
  messageDesc(file_main_session_manager, 2);

/**
 * @generated from message GetSessionResponse
 */
export type GetSessionResponse = Message<"GetSessionResponse"> & {
  /**
   * @generated from field: bool session_active = 1;
   */
  sessionActive: boolean;

  /**
   * @generated from field: string simulator_endpoint = 2;
   */
  simulatorEndpoint: string;

  /**
   * @generated from field: string error_message = 3;
   */
  errorMessage: string;
};

/**
 * Describes the message GetSessionResponse.
 * Use `create(GetSessionResponseSchema)` to create a new message.
 */
export const GetSessionResponseSchema: GenMessage<GetSessionResponse> = /*@__PURE__*/
  messageDesc(file_main_session_manager, 3);

/**
 * @generated from message EndSessionRequest
 */
export type EndSessionRequest = Message<"EndSessionRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string token = 2;
   */
  token: string;
};

/**
 * Describes the message EndSessionRequest.
 * Use `create(EndSessionRequestSchema)` to create a new message.
 */
export const EndSessionRequestSchema: GenMessage<EndSessionRequest> = /*@__PURE__*/
  messageDesc(file_main_session_manager, 4);

/**
 * @generated from message EndSessionResponse
 */
export type EndSessionResponse = Message<"EndSessionResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string error_message = 2;
   */
  errorMessage: string;
};

/**
 * Describes the message EndSessionResponse.
 * Use `create(EndSessionResponseSchema)` to create a new message.
 */
export const EndSessionResponseSchema: GenMessage<EndSessionResponse> = /*@__PURE__*/
  messageDesc(file_main_session_manager, 5);

/**
 * @generated from message KeepAliveRequest
 */
export type KeepAliveRequest = Message<"KeepAliveRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string token = 2;
   */
  token: string;
};

/**
 * Describes the message KeepAliveRequest.
 * Use `create(KeepAliveRequestSchema)` to create a new message.
 */
export const KeepAliveRequestSchema: GenMessage<KeepAliveRequest> = /*@__PURE__*/
  messageDesc(file_main_session_manager, 6);

/**
 * @generated from message KeepAliveResponse
 */
export type KeepAliveResponse = Message<"KeepAliveResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message KeepAliveResponse.
 * Use `create(KeepAliveResponseSchema)` to create a new message.
 */
export const KeepAliveResponseSchema: GenMessage<KeepAliveResponse> = /*@__PURE__*/
  messageDesc(file_main_session_manager, 7);

/**
 * @generated from message GetSessionStateRequest
 */
export type GetSessionStateRequest = Message<"GetSessionStateRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string token = 2;
   */
  token: string;
};

/**
 * Describes the message GetSessionStateRequest.
 * Use `create(GetSessionStateRequestSchema)` to create a new message.
 */
export const GetSessionStateRequestSchema: GenMessage<GetSessionStateRequest> = /*@__PURE__*/
  messageDesc(file_main_session_manager, 8);

/**
 * @generated from message GetSessionStateResponse
 */
export type GetSessionStateResponse = Message<"GetSessionStateResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string simulator_id = 2;
   */
  simulatorId: string;

  /**
   * @generated from field: string simulator_endpoint = 3;
   */
  simulatorEndpoint: string;

  /**
   * @generated from field: int64 session_created_at = 4;
   */
  sessionCreatedAt: bigint;

  /**
   * @generated from field: int64 last_active = 5;
   */
  lastActive: bigint;

  /**
   * @generated from field: string error_message = 6;
   */
  errorMessage: string;
};

/**
 * Describes the message GetSessionStateResponse.
 * Use `create(GetSessionStateResponseSchema)` to create a new message.
 */
export const GetSessionStateResponseSchema: GenMessage<GetSessionStateResponse> = /*@__PURE__*/
  messageDesc(file_main_session_manager, 9);

/**
 * @generated from service SessionManagerService
 */
export const SessionManagerService: GenService<{
  /**
   * @generated from rpc SessionManagerService.CreateSession
   */
  createSession: {
    methodKind: "unary";
    input: typeof CreateSessionRequestSchema;
    output: typeof CreateSessionResponseSchema;
  },
  /**
   * @generated from rpc SessionManagerService.GetSession
   */
  getSession: {
    methodKind: "unary";
    input: typeof GetSessionRequestSchema;
    output: typeof GetSessionResponseSchema;
  },
  /**
   * @generated from rpc SessionManagerService.EndSession
   */
  endSession: {
    methodKind: "unary";
    input: typeof EndSessionRequestSchema;
    output: typeof EndSessionResponseSchema;
  },
  /**
   * @generated from rpc SessionManagerService.KeepAlive
   */
  keepAlive: {
    methodKind: "unary";
    input: typeof KeepAliveRequestSchema;
    output: typeof KeepAliveResponseSchema;
  },
  /**
   * @generated from rpc SessionManagerService.GetSessionState
   */
  getSessionState: {
    methodKind: "unary";
    input: typeof GetSessionStateRequestSchema;
    output: typeof GetSessionStateResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_main_session_manager, 0);


