apiVersion: v1
kind: Service
metadata:
  name: iexgsimulator
spec:
  ports:
    - name: fix-server
      port: 9876
      targetPort: fix-server
    - name: open-api
      port: 8501
      targetPort: open-api
    - name: grpc
      port: 50051
      targetPort: grpc
  selector:
    app: iexgsimulator
  type: ClusterIP
