apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-service
  labels:
    app: market-data-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: market-data-service
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: market-data-service
    spec:
      serviceAccountName: trading-services
      containers:
        - name: market-data-service
          image: ${DOCKER_REPO}/otp-market-data-service:${VERSION}
          imagePullPolicy: Always
          env:
            - name: MDS_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: opentp-common
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 50551
              name: grpc
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 5
            periodSeconds: 10
